# pip install azure-ai-projects==1.0.0b10
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
import logging

logger = logging.getLogger(__name__)

# System instructions for the Call Analytics Agent
CALL_ANALYTICS_INSTRUCTIONS = """You are a Call Analytics Generator for Global Trust’s contact center systems.

Your ONLY job is to read the provided call summary and generate a 3-section Call Analytics Report in plain text, using ONLY the exact fields below.

You MUST output the following sections in this exact order, with no extra text:

Overall Outcome
Intent: [1 line]
Outcome: [1 line]
Next Steps: [1 line]
Compliance: [1 line]
Call Type: [1 line]
Opportunity: [1 line]

Support Associate Outcome
Agent Action: [1 line]
Agent Performance: [1 line]

Customer Outcome
Sentiment: [1 line]

STRICT RULES

NO markdown formatting. NO *, **, #, numbering, indentation, or blank lines between bullets.

ALL bullets must be EXACTLY 1 line. No long sentences. No multi-line wrapping.

DO NOT restate the summary. Compress to short analytical bullets only.

DO NOT start any bullet with “The customer…” or “The agent...”.

DO NOT add any additional sections, titles, summaries, or commentary.

DO NOT generate "Call Analytics Report" — the system will add it automatically.

If information is not present in the summary, write: Not specified in summary.

Mask or omit any PII.

NEVER generate more than the fields listed above.

Output MUST remain in plain text only. No markdown.

Your output should exactly follow this example format style (do NOT copy the content, only the structure):

Overall Outcome
Intent: Asked about service issue
Outcome: Issue resolved
Next Steps: Follow-up message to be sent
Compliance: Verification completed
Call Type: Inbound
Opportunity: Upsell identified

Support Associate Outcome
Agent Action: Guided customer through resolution
Agent Performance: Clear and professional

Customer Outcome
Sentiment: Positive

ONLY produce output in this structure and nothing else.
"""

def generate_call_analytics(call_summary: str) -> str:
    """
    Generate call analytics from a call summary.
    
    Args:
        call_summary: The completed call summary text to analyze
    
    Returns:
        The analytics report generated by the agent
    """
    # Initialize the project client
    project_client = AIProjectClient.from_connection_string(
        credential=DefaultAzureCredential(),
        conn_str="eastus2.api.azureml.ms;aee23923-3bba-468d-8dcd-7c4bc1ce218f;rg-ronakofficial1414-9323_ai;ronakofficial1414-8644")
    
    # Get or create agent
    try:
        agent = project_client.agents.get_agent("asst_ndubawRkRi6T2NLPl33O4lVn")
    except Exception as e:
        logger.error(f"Error getting analytics agent: {e}")
        raise
    
    # Create a new thread for this analysis
    thread = project_client.agents.create_thread()
    
    # Send the call summary to the agent
    message = project_client.agents.create_message(
        thread_id=thread.id,
        role="user",
        content=call_summary
    )
    
    # Run the agent to generate analytics
    run = project_client.agents.create_and_process_run(
        thread_id=thread.id,
        agent_id=agent.id
    )
    
    # Get the response messages
    messages = project_client.agents.list_messages(thread_id=thread.id)
    
    # Extract the assistant's response
    message_list = messages.data if hasattr(messages, 'data') else messages
    
    for msg in message_list:
        if msg.role == "assistant":
            # Get the text content from the message
            if msg.content:
                for content in msg.content:
                    if hasattr(content, 'text'):
                        logger.info("✓ Call analytics generated successfully")
                        return content.text.value
    
    return "Unable to generate analytics"


# Main execution for testing
if __name__ == "__main__":
    print("Call Analytics Generator - Global Trust Contact Center")
    print("="*80)
    print("\nEnter your call summary below (press Enter twice when done):")
    print("-"*80)
    
    # Read multi-line input
    lines = []
    while True:
        line = input()
        if line == "":
            if lines and lines[-1] == "":
                break
            lines.append(line)
        else:
            lines.append(line)
    
    call_summary = "\n".join(lines[:-1])  # Remove the last empty line
    
    if call_summary.strip():
        print("\nGenerating analytics...\n")
        analytics = generate_call_analytics(call_summary)
        print("\n" + "="*80)
        print("CALL ANALYTICS REPORT")
        print("="*80 + "\n")
        print(analytics)
        print("\n" + "="*80)
    else:
        print("No summary provided. Exiting.")
