"""
Test script for Call Analytics Generator

This script tests the call analytics generation by passing a sample call summary
EXACTLY as generated by the summarizer agent.
"""

from call_analytics import generate_call_analytics

# Sample call summary - exact format from summarizer agent
SAMPLE_SUMMARY = """A) Short Summary

Customer Raj Kapoor contacted Global Trust Bank regarding his credit card that was returned due to non-delivery. This was his fourth call in ten days. The agent verified his identity, confirmed the card was dispatched but returned when he was unavailable. The agent processed a re-dispatch request to the same address and confirmed the new delivery timeline of 3-5 business days. An email confirmation with tracking details would be sent shortly. The agent also offered an upgrade to the Gold Cashback Credit Card with enhanced rewards and benefits. Customer expressed interest and was informed that the upgrade requires eligibility verification and internal approvals. The agent indicated a transfer to a Card Upgrade Expert for further assistance.

B) Structured Summary

1. Customer Intent:
Inquired about credit card delivery status after previous dispatch was returned.

2. Customer Behavior:
Cooperative and responsive throughout the interaction.

3. Overall Sentiment:
Positive – customer remained calm and engaged with upgrade offer.

4. Key Details Discussed:
Card dispatched via Bluedart but returned due to customer unavailability. Re-dispatch processed to same registered address. Delivery expected in 3-5 business days. Email confirmation with tracking to be sent. Upgrade offer for Gold Cashback Credit Card presented with benefits including higher cashback limits, airport lounge access, and additional reward points on dining and travel.

5. Agent Actions:
Verified customer identity, checked dispatch history, processed re-dispatch request, provided delivery timeline, offered card upgrade opportunity, explained upgrade benefits and requirements.

6. Resolution / Outcome:
Re-dispatch request confirmed. Customer informed of delivery timeline and tracking notification. Customer showed interest in card upgrade.

7. Next Steps:
Email confirmation with tracking details to be sent. Transfer to Card Upgrade Expert for eligibility verification and approval process."""

def main():
    print("="*80)
    print("CALL ANALYTICS GENERATOR - TEST SCRIPT")
    print("="*80)
    print("\nTesting analytics generation with sample call summary...")
    print("-"*80)
    
    try:
        # Generate analytics
        print("\n🔄 Generating analytics...\n")
        analytics = generate_call_analytics(SAMPLE_SUMMARY)
        
        # Display results
        print("="*80)
        print("CALL ANALYTICS REPORT")
        print("="*80)
        print()
        print(analytics)
        print()
        print("="*80)
        print("✅ Analytics generated successfully!")
        print("="*80)
        
    except Exception as e:
        print(f"\n❌ Error generating analytics: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
